### PR TITLE
fixed potential naming conflicts with Google Firebase sdk

### PR DESCRIPTION
**Pull request by kasradzenika**
fixing issue https://github.com/dkrprasetya/simple-firebase-unity/issues/10

fixed the following scenario:
- in unity:

```
using SimpleFirebaseUnity;

void Start(){
    Firebase f = Firebase.CreateNew(...);
}
```
when Google Firebase sdk is also present in the project the following error is thrown:

> error CS0118: 'Firebase' is a 'namespace' but a 'type' was expected

to fix this in this pull request I renamed all the classes in SimpleFirebaseUnity namespace with "SimpleFirebase" prefix (e.g. SimpleFirebaseError, SimpleDataSnapshot... )

### CODE REVIEW

**Comment by kasradzenika** [comment]
EDIT: [here is the updated SampleScript.cs](https://codepaste.net/rcmg1s) from the Unity sample project using the new class names

**Comment by dkrprasetya** [comment]
Hi kasradzenika, thank you for helping! We sure need to refactor these soon. 

Since I’ve been lazy for not checking this repo for a while, I’m taking this opportunity to review again the API then update things up this week. I’ll merge afterwards.

**Review by veereshkumbargs — COMMENTED** [review]
I too want to edit the code but not possible. I have downloaded the asset from unity asset store but getting same error please help

**Comment by dkrprasetya** [comment]
Since the problem has been resolved, I am closing this pull request.

Thank you for helping!

**Pull request closed without merging**
